development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: myapp_development
  pool: 5
  username: myapp
  password: password1

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: myapp_test
  pool: 5
  username: myapp
  password: password1

production:
  <<: *default
  adapter: postgresql
  host: localhost
  database: production
  encoding: UTF8

